agents:
  queue: default
steps:
  - key: "build"
    label: ":hammer_and_wrench: Build"
    commands:
      - bundle install 
      - rake
    artifact_paths: "*.deb"

  - label: ":ubuntu: Publish"
    depends_on: "build"
    plugins:
      - publish-to-packages#v2.1.0:
          artifacts: "*.deb"
          registry: "cnunciato-playground/oidc-example"
